version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=HIERdbmysql
      - MYSQL_USER=appusr
      - MYSQL_PASSWORD=l3tmeinT4
      - MYSQL_ROOT_PASSWORD=l3tmeinT4
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.30.0.10
    restart: always
  HIER_website:
    image: aspnetapp
    container_name: HIER_website
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - /home/vagrant/.aspnet/https:/https/
    networks:
      - app_net
    restart: always

  HIER_API:
    image: aspnet-api
    container_name: HIER_API
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - /home/vagrant/.aspnet/https:/https/
    networks:
      - app_net
    restart: always
volumes:
  mysql-data:

networks:
  app_net:
    external: true
